# Generated by Django 4.1.6 on 2023-02-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date', models.DateTimeField(verbose_name='Дата обращения')),
                ('text', models.CharField(max_length=300, verbose_name='Тип обращения')),
            ],
        ),
    ]
