# Generated by Django 4.1.6 on 2023-02-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table1',
            options={'verbose_name': 'История обращений', 'verbose_name_plural': 'История обращений'},
        ),
        migrations.AddField(
            model_name='table1',
            name='bankId',
            field=models.IntegerField(default=0, verbose_name='id банка'),
        ),
        migrations.AddField(
            model_name='table1',
            name='clientId',
            field=models.IntegerField(default=0, verbose_name='id клиента'),
        ),
    ]
