# Generated by Django 4.1.6 on 2023-02-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_table1_callhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=50, verbose_name='Адрес')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('bankType', models.CharField(max_length=100, verbose_name='Тип банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='BankType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankId', models.IntegerField(default=0, verbose_name='id банка')),
                ('bankType', models.CharField(max_length=100, verbose_name='Тип банка')),
            ],
            options={
                'verbose_name': 'Тип банка',
                'verbose_name_plural': 'Типы банков',
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRelible', models.BooleanField(default=False, verbose_name='Надёжный')),
                ('isVIP', models.BooleanField(default=False, verbose_name='VIP')),
                ('type', models.BooleanField(verbose_name='Тип клиента')),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('phoneNumber', models.IntegerField(default=0, verbose_name='Номер телефона')),
                ('clientType', models.IntegerField(default=0, verbose_name='Тип клиента')),
            ],
            options={
                'verbose_name': 'Информация о клиенте',
                'verbose_name_plural': 'Информация о клиентах',
            },
        ),
    ]
