# Generated by Django 4.1.6 on 2023-02-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bank_banktype_clientgroup_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bankName',
            field=models.CharField(max_length=50, verbose_name='Название банка'),
        ),
    ]
