services:
  django:
    build: .
    container_name: django
    command: gunicorn lab7.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postres
      - POSTGRES_USER=postres
      - POSTGRES_PASSWORD=postres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib.postgresql/data/

volumes:
  pgdbdata: null