# Generated by Django 4.1.6 on 2023-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('post', models.IntegerField(verbose_name='Номер поста')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
            ],
            options={
                'verbose_name': 'Лайк пользователя',
                'verbose_name_plural': 'Лайки пользователей',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор поста')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
                ('header', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('nickname', models.TextField(primary_key=True, serialize=False, verbose_name='Никнейм')),
                ('likes_sum', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг пользователя',
                'verbose_name_plural': 'Рейтинг пользователей',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('pid', models.IntegerField(verbose_name='Идентификатор поста')),
                ('tag', models.TextField(verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег поста',
                'verbose_name_plural': 'Теги постов',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='Индекс')),
                ('username', models.TextField(unique=True, verbose_name='Никнейм')),
                ('utype', models.BooleanField(verbose_name='Является автором')),
                ('uadmin', models.BooleanField(default=False, verbose_name='Администратор?')),
                ('password1', models.TextField(verbose_name='Пароль')),
                ('password2', models.TextField(verbose_name='Пароль еще раз')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
